version: '3'

tasks:
  build:
    deps:
      - set-new-version
    cmds:
      - yarn build

  publish:
    deps:
      - set-new-version
    cmds:
      - yarn publish-image

  set-new-version:
    cmds:
      - yarn set-new-version
