version: '3'

env:
  ROOT_PATH: $(pwd)

tasks:
  build:
    deps:
      - set-new-version
    cmds:
      - yarn workspaces run build

  publish:
    deps:
      - set-new-version
    cmds:
      - yarn workspaces run publish-image

# Deps
  set-new-version:
    cmds:
      - yarn set-new-version

  changed-images:
    cmds:
      # need to handle when no change
      - yarn --silent changed | jq --raw-output .[].name > changed.txt

  if-changed:
    cmds:
      - task: changed-images
      - yarn workspaces run ifChanged
