version: '3'

tasks:
  build:
    deps:
      - set-new-version
    cmds:
      - yarn workspaces run build

  publish:
    deps:
      - set-new-version
    cmds:
      - yarn workspaces run publish-image

# Deps
  set-new-version:
    cmds:
      - yarn set-new-version
