version: '3'

env:
  ROOT_PATH: $(pwd)

tasks:
  build_and_publish_image:
    deps:
      - set-new-version
    cmds:
      - yarn workspaces run build_and_publish_image

  # set new version in package.json if changes detected
  set-new-version:
    dpes:
      - changed-images
    cmds:
      - yarn set-new-version

  changed-images:
    cmds:
      - yarn --silent changed | jq --raw-output .[].name > changed.txt
